# Generated by Django 2.2.1 on 2019-05-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_cred'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenuN',
            fields=[
                ('key_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('food_name1', models.CharField(max_length=50, null=True)),
                ('food_name2', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SelfListN',
            fields=[
                ('self_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('self_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentN',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('std_type', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.StudentN')),
            ],
        ),
        migrations.CreateModel(
            name='CouponN',
            fields=[
                ('coupon_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.BooleanField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.FoodMenuN')),
                ('self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SelfListN')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.StudentN')),
            ],
        ),
    ]
