# Generated by Django 2.2.1 on 2019-05-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_couponn_foodmenun_selflistn_studentn_transactionn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponn',
            old_name='self',
            new_name='self_id',
        ),
    ]
