# Generated by Django 2.2.1 on 2019-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190524_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionn',
            name='price',
            field=models.FloatField(),
        ),
    ]
